[package]
name = "delta_test"
version = "0.1.0"
edition = "2021"

[dependencies]
deltalake = {version = "0.22.3"}
tokio = {version = "1.42.0", features = ["macros", "rt-multi-thread" ]}
serde = "1"
serde_json = "1"
