[package]
name = "string_parser_udf"
version = "0.1.0"
edition = "2021"

[lib]
name = "string_parser_udf"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
regex = "1.10"
serde_json = "1.0"
