
## Author: Matt Martin
## Date: 2023-11-06
## Desc: Docker Container for Iceberg

ARG REGISTRY=quay.io
ARG OWNER=jupyter
ARG BASE_CONTAINER=$REGISTRY/$OWNER/scipy-notebook
FROM $BASE_CONTAINER

LABEL maintainer="Matt Martin"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

## get java
ARG openjdk_version="17"

RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    "openjdk-${openjdk_version}-jre-headless" \
    ca-certificates-java && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Spark installation
WORKDIR /tmp


# Configure IPython system-wide
COPY ipython_kernel_config.py "/etc/ipython/"
RUN fix-permissions "/etc/ipython/"

USER ${NB_UID}

RUN pip install \
    pyspark==3.5 \
    pyiceberg==0.5.0

## get the pyspark iceberg runtime and sql extensions jars

ARG ICE_RT=iceberg-spark-runtime-3.5_2.12-1.4.2.jar
RUN curl -Lo "/opt/conda/lib/python3.11/site-packages/pyspark/jars/${ICE_RT}" \
    "https://search.maven.org/remotecontent?filepath=org/apache/iceberg/iceberg-spark-runtime-3.5_2.12/1.4.2/${ICE_RT}" \
  && chmod u+x "/opt/conda/lib/python3.11/site-packages/pyspark/jars/${ICE_RT}"

ARG ICE_SQL_EXT=iceberg-spark-extensions-3.5_2.12-1.4.2.jar
RUN curl -Lo "/opt/conda/lib/python3.11/site-packages/pyspark/jars/${ICE_SQL_EXT}" \
    "https://search.maven.org/remotecontent?filepath=org/apache/iceberg/iceberg-spark-extensions-3.5_2.12/1.4.2/${ICE_SQL_EXT}" \
  && chmod u+x "/opt/conda/lib/python3.11/site-packages/pyspark/jars/${ICE_SQL_EXT}"


RUN mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"


#add example delta python file
COPY iceberg_template.ipynb "${HOME}"

WORKDIR "${HOME}"
EXPOSE 4040