#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TF_DIR="$PROJECT_ROOT/terraform_ecs_runner_taskdefs"
ENV_EXAMPLE="$PROJECT_ROOT/.env.example"
ENV_FILE="$PROJECT_ROOT/.env"

usage() {
  cat <<'EOF'
Usage:
  ./deploy/render_airflow_env.sh [--seed-s3-uri s3://...] [--orders-s3-uri s3://...] [--cust-s3-uri s3://...] [--lineitem-s3-uri s3://...]

Description:
  Creates .env for local Airflow by reading Terraform outputs from terraform_ecs_runner_taskdefs.
EOF
}

ORDERS_S3_URI="s3://s3-sales-agg-test/scripts/orders_etl.py"
CUST_S3_URI="s3://s3-sales-agg-test/scripts/cust_etl.py"
SEED_S3_URI="s3://s3-sales-agg-test/scripts/seed_tpch_raw_data.py"
LINEITEM_S3_URI="s3://s3-sales-agg-test/scripts/lineitem_etl.py"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed-s3-uri)
      SEED_S3_URI="${2:-}"
      shift 2
      ;;
    --orders-s3-uri)
      ORDERS_S3_URI="${2:-}"
      shift 2
      ;;
    --cust-s3-uri)
      CUST_S3_URI="${2:-}"
      shift 2
      ;;
    --lineitem-s3-uri)
      LINEITEM_S3_URI="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown argument '$1'" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ ! -f "$ENV_EXAMPLE" ]]; then
  echo "Error: .env.example not found at $ENV_EXAMPLE" >&2
  exit 1
fi

if [[ ! -d "$TF_DIR" ]]; then
  echo "Error: terraform directory not found at $TF_DIR" >&2
  exit 1
fi

if ! command -v terraform >/dev/null 2>&1; then
  echo "Error: terraform is required." >&2
  exit 1
fi

CLUSTER_NAME="$(terraform -chdir="$TF_DIR" output -raw ecs_cluster_name)"
TASK_DEF_ARN="$(terraform -chdir="$TF_DIR" output -raw medium_runner_task_definition_arn)"
CONTAINER_NAME="$(terraform -chdir="$TF_DIR" output -raw medium_runner_container_name)"
SECURITY_GROUP_ID="$(terraform -chdir="$TF_DIR" output -raw security_group_id)"
SUBNETS_CSV="$(terraform -chdir="$TF_DIR" output -json subnet_ids | tr -d '[]"[:space:]')"
CLUSTER_ARN="$(terraform -chdir="$TF_DIR" output -raw ecs_cluster_arn)"
AWS_REGION="$(echo "$CLUSTER_ARN" | cut -d':' -f4)"
TASK_DEF_RESOURCE="${TASK_DEF_ARN#arn:aws:ecs:*:*:}"
AWS_ACCT_ID_ENV="${AWS_ACCT_ID:-}"

if [[ -z "$AWS_ACCT_ID_ENV" ]]; then
  echo "Error: AWS_ACCT_ID environment variable must be set before rendering .env" >&2
  exit 1
fi

TASK_DEF_ARN="arn:aws:ecs:${AWS_REGION}:${AWS_ACCT_ID_ENV}:${TASK_DEF_RESOURCE}"

cp "$ENV_EXAMPLE" "$ENV_FILE"

if grep -q '^AWS_PROFILE=' "$ENV_FILE"; then
  sed -i '' 's/^AWS_PROFILE=.*/AWS_PROFILE=default/' "$ENV_FILE"
else
  echo 'AWS_PROFILE=default' >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" <<EOF

# Auto-generated by deploy/render_airflow_env.sh
AIRFLOW_ECS_CLUSTER=$CLUSTER_NAME
AIRFLOW_ECS_TASK_DEFINITION=$TASK_DEF_ARN
AIRFLOW_ECS_CONTAINER_NAME=$CONTAINER_NAME
AIRFLOW_ECS_SUBNETS=$SUBNETS_CSV
AIRFLOW_ECS_SECURITY_GROUPS=$SECURITY_GROUP_ID
AIRFLOW_ECS_REGION=$AWS_REGION
AWS_REGION=$AWS_REGION
AWS_DEFAULT_REGION=$AWS_REGION
SEED_SCRIPT_S3_URI=$SEED_S3_URI
ORDERS_SCRIPT_S3_URI=$ORDERS_S3_URI
CUST_SCRIPT_S3_URI=$CUST_S3_URI
LINEITEM_SCRIPT_S3_URI=$LINEITEM_S3_URI
EOF

echo "Wrote $ENV_FILE"
