[project]
name = "big-data-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.1",
    "polars>=1.34.0",
    "pyspark==3.5.4",
]
