[package]
name = "rust_bears"
version = "0.1.0"
edition = "2021"

[dependencies]
polars-lazy = "0.38.3"
polars = { version = "0.38.3", features = ["lazy", "strings", "regex", "to_dummies","parquet"] }
glob = "0.3"