[package]
name = "rust_bears"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono-tz = "0.5"
chrono = "0.4"
polars-lazy = "0.40.0"
polars = { version = "0.40.0", features = ["lazy", "strings", "regex", "to_dummies","parquet"] }