[package]
name = "rust_to_python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_to_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
num-format = "0.4"
