[package]
name = "fast_writer"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }


[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "misc_utils"