[package]
name = "rust_con"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
tokio-util = { version = "0.6", features = ["codec", "io"] }