'Public Class cScriptCompTest
'    '--------------------------------------------------------------------------------------
'    'add row id via script transformation

'    'set the script task component meta data
'    Dim row_id_script_tsfm_CMDT As IDTSComponentMetaData100 = df_task.ComponentMetaDataCollection.[New]()
'        row_id_script_tsfm_CMDT.ComponentClassID = pkg_app.PipelineComponentInfos("Script Component").CreationName
'        'row_id_script_tsfm_CMDT.Instantiate()
'        'row_id_script_tsfm_CMDT.Name = "Add Row ID"

'        'set the component wrapper
'        Dim rid_script_wrapper As CManagedComponentWrapper = row_id_script_tsfm_CMDT.Instantiate()
'        rid_script_wrapper.ProvideComponentProperties()

'        'add the edis row id
'        Dim outputColl_id As String = row_id_script_tsfm_CMDT.OutputCollection(0).ID.ToString
'        rid_script_wrapper.InsertOutputColumnAt(outputColl_id, 0, "EDIS_SRC_ROW_ID", "EDIS Source Row ID")
'        Dim edis_src_row_id_marker As String = row_id_script_tsfm_CMDT.OutputCollection(0).OutputColumnCollection.Item(0).ID

'        'update to bigint
'        rid_script_wrapper.SetOutputColumnDataTypeProperties(outputColl_id, edis_src_row_id_marker, DataType.DT_I8, 0, 0, 0, 0)

'        'set script language
'        rid_script_wrapper.SetComponentProperty("ScriptLanguage", "VisualBasic")

'        'set the vb code

'        Dim vb_script As String = ""

'        vb_script += vbCrLf + vbCrLf
'        vb_script += "'***************************************************************************************" + vbCrLf
'        vb_script += "'This code was generated by EDIS for purposes of tracking the source row ID. " + vbCrLf
'        vb_script += "'For more information, visit www.sqletl.com " + vbCrLf
'        vb_script += "'***************************************************************************************" + vbCrLf
'        vb_script += vbCrLf + vbCrLf

'        vb_script += "Imports System" + vbCrLf
'        vb_script += "Imports System.Data" + vbCrLf
'        vb_script += "Imports System.Math" + vbCrLf
'        vb_script += "Imports Microsoft.SqlServer.Dts.Pipeline.Wrapper" + vbCrLf
'        vb_script += "Imports Microsoft.SqlServer.Dts.Runtime.Wrapper" + vbCrLf
'        vb_script += vbCrLf
'        vb_script += "<Microsoft.SqlServer.Dts.Pipeline.SSISScriptComponentEntryPointAttribute> _" + vbCrLf
'        vb_script += "  <CLSCompliant(False)> _ " + vbCrLf
'        vb_script += "Public Class ScriptMain" + vbCrLf
'        vb_script += "      Inherits UserComponent" + vbCrLf
'        vb_script += vbCrLf
'        vb_script += "      Private row_id As Long" + vbCrLf
'        vb_script += "      Public Overrides Sub PreExecute()" + vbCrLf
'        vb_script += "          MyBase.PreExecute()" + vbCrLf
'        vb_script += "          row_id = 0" + vbCrLf
'        vb_script += "      End Sub" + vbCrLf
'        vb_script += vbCrLf
'        vb_script += "      Public Overrides Sub PostExecute()" + vbCrLf
'        vb_script += "          MyBase.PostExecute()" + vbCrLf
'        vb_script += "      End Sub" + vbCrLf
'        vb_script += vbCrLf
'        vb_script += "      Public Overrides Sub Input0_ProcessInputRow(ByVal Row As Input0Buffer)" + vbCrLf
'        vb_script += "          row_id += 1" + vbCrLf
'        vb_script += "          Row.EDISSRCROWID = row_id" + vbCrLf
'        vb_script += "      End Sub" + vbCrLf
'        vb_script += vbCrLf
'        vb_script += "End Class" + vbCrLf

'        'isolate the inner component
'        Dim scriptComp As Microsoft.SqlServer.Dts.Pipeline.ScriptComponentHost = TryCast(TryCast(rid_script_wrapper, IDTSManagedComponent100).InnerObject, Microsoft.SqlServer.Dts.Pipeline.ScriptComponentHost)

'        scriptComp.Initialize()

'        'note: create and save the project first, then "put"/replace the existing main code
'        scriptComp.CreateNewProject("edisRowTracker", True, True)
'        scriptComp.SaveScriptProject()
'        scriptComp.PutSourceCode("main.vb", "UTF8", vb_script)

'        row_id_script_tsfm_CMDT.Name = "EDIS - Add Source Row ID"

'        'attach source to row id
'        df_task.PathCollection.[New]().AttachPathAndPropagateNotifications(df_src_comp.OutputCollection(0), row_id_script_tsfm_CMDT.InputCollection(0))
'End Class
