'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EDIS_App_Installer.Resource", GetType(Resource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property EDIS_EXE() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("EDIS_EXE", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''    try 
        '''    {
        '''        $ErrorActionPreference = &quot;Stop&quot;
        '''
        '''		$log_file = {LOG_FILE}
        '''		$dll_path = {DLL_PATH}
        '''	
        '''        ### Load Assembly to GAC
        '''        [System.Reflection.Assembly]::LoadWithPartialName(&quot;System.EnterpriseServices&quot;) | Out-Null     
        '''        $publish = New-Object System.EnterpriseServices.Internal.Publish            
        '''        $publish.GacInstall($dll_path) 
        '''	
        '''
        '''	Add-Content $log_file &quot;success&quot;
        '''
        '''    }
        '''    Catch [System.Exception] 
        '''    {
        '''        $err_msg = $_.Exception.Message
        '''    [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property EDIS_GAC() As String
            Get
                Return ResourceManager.GetString("EDIS_GAC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property MDDataTechCLR() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MDDataTechCLR", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 	
        '''	
        '''	/*
        '''	*/
        '''	
        '''	
        '''	USE SSISDB
        '''
        '''	GO
        '''
        '''	-- DISABLE MS TRIGGER ON SSISDB
        '''	
        '''	IF EXiSTS(select * from SSISDB.sys.triggers where name = &apos;ddl_cleanup_object_permissions&apos;)
        '''		BEGIN
        '''			IF EXISTS (SELECT is_disabled from SSISDB.sys.triggers where name = &apos;ddl_cleanup_object_permissions&apos; and is_disabled = 0)
        '''				BEGIN
        '''					EXEC SSISDB..sp_executesql N&apos;DISABLE TRIGGER ddl_cleanup_object_permissions ON DATABASE&apos;
        '''					--print &apos;trigger disabled&apos;
        '''				END
        '''		END
        '''
        '''	GO
        '''
        '''	-- Change DB_OWNER to SA
        '''	IF NOT exis [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property MDDT_Install() As String
            Get
                Return ResourceManager.GetString("MDDT_Install", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''	-- EDIS Uninstall Scripts
        '''
        '''	-- =======================================================================================================================================
        '''	-- Drop Procs, tables, views, functions
        '''
        '''	declare @cmd nvarchar(max)
        '''	select @cmd = isnull(@cmd,&apos;&apos;)+
        '''		concat(&apos;if object_id(&apos;&apos;&apos;,object_schema_name(object_id),&apos;.&apos;,name,&apos;&apos;&apos;) is not null drop &apos;
        '''			,case type 
        '''				when &apos;U&apos; then &apos;table &apos;
        '''				when &apos;P&apos; then &apos;proc &apos;
        '''				WHEN &apos;PC&apos; then &apos;proc &apos;
        '''				when &apos;FN&apos; then &apos;function &apos;
        '''				when &apos;F [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property MDDT_Remove() As String
            Get
                Return ResourceManager.GetString("MDDT_Remove", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sqletl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sqletl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Third Party Notices for SQL ETL EDIS, MD Data Technologies, LLC
        '''
        '''------------------------------------------- START OF THIRD PARTY NOTICES ----------------------------
        '''Do Not Translate or Localize
        '''This file is based on or incorporates material from the projects listed below (Third Party IP). The original copyright notice and the license under which MD Data Technologies, LLC (SQLETL) received such Third Party IP, are set forth below. Such licenses and notices are provided for informational purposes only.  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Third_Party_License_Notice() As String
            Get
                Return ResourceManager.GetString("Third_Party_License_Notice", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
